In [15]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
import numpy as np
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
sent = [
    'the bowl of cereal',
    'the cup of coffee',
    'the bottle of soda',
    'I am a dedicated learner',
    'I am a talented artist',
    'understand the importance of teamwork',
    'your ideas are creative',
    'the plate of cookies',
    'the jar of jam',
    'the cup of soup',
    'I am a passionate reader',
    'I am a skilled programmer',
    'remember the value of friendship',
    'your music is inspiring',
    'the slice of bread',
    'the glass of lemonade',
    'the bowl of fruit',
    'I am a curious explorer',
    'I am a supportive friend',
    'discover the joy of learning'
]


In [17]:
print(sent)

['the bowl of cereal', 'the cup of coffee', 'the bottle of soda', 'I am a dedicated learner', 'I am a talented artist', 'understand the importance of teamwork', 'your ideas are creative', 'the plate of cookies', 'the jar of jam', 'the cup of soup', 'I am a passionate reader', 'I am a skilled programmer', 'remember the value of friendship', 'your music is inspiring', 'the slice of bread', 'the glass of lemonade', 'the bowl of fruit', 'I am a curious explorer', 'I am a supportive friend', 'discover the joy of learning']


In [18]:
vocab_size=10000

In [19]:
one_hot_repr=[one_hot(words,vocab_size)for words in sent]
one_hot_repr

[[6936, 4395, 6829, 4659],
 [6936, 5644, 6829, 6896],
 [6936, 927, 6829, 7833],
 [1439, 5234, 9341, 7938, 944],
 [1439, 5234, 9341, 5851, 9072],
 [6265, 6936, 6943, 6829, 8046],
 [732, 533, 4025, 4709],
 [6936, 3138, 6829, 3362],
 [6936, 4256, 6829, 6826],
 [6936, 5644, 6829, 6458],
 [1439, 5234, 9341, 9198, 9364],
 [1439, 5234, 9341, 2782, 7350],
 [6195, 6936, 6116, 6829, 7295],
 [732, 6009, 869, 6369],
 [6936, 4649, 6829, 9287],
 [6936, 5659, 6829, 2897],
 [6936, 4395, 6829, 1947],
 [1439, 5234, 9341, 2983, 6146],
 [1439, 5234, 9341, 9182, 5115],
 [9993, 6936, 8642, 6829, 6965]]

In [20]:
sent_length=10
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0 6936 4395 6829 4659]
 [   0    0    0    0    0    0 6936 5644 6829 6896]
 [   0    0    0    0    0    0 6936  927 6829 7833]
 [   0    0    0    0    0 1439 5234 9341 7938  944]
 [   0    0    0    0    0 1439 5234 9341 5851 9072]
 [   0    0    0    0    0 6265 6936 6943 6829 8046]
 [   0    0    0    0    0    0  732  533 4025 4709]
 [   0    0    0    0    0    0 6936 3138 6829 3362]
 [   0    0    0    0    0    0 6936 4256 6829 6826]
 [   0    0    0    0    0    0 6936 5644 6829 6458]
 [   0    0    0    0    0 1439 5234 9341 9198 9364]
 [   0    0    0    0    0 1439 5234 9341 2782 7350]
 [   0    0    0    0    0 6195 6936 6116 6829 7295]
 [   0    0    0    0    0    0  732 6009  869 6369]
 [   0    0    0    0    0    0 6936 4649 6829 9287]
 [   0    0    0    0    0    0 6936 5659 6829 2897]
 [   0    0    0    0    0    0 6936 4395 6829 1947]
 [   0    0    0    0    0 1439 5234 9341 2983 6146]
 [   0    0    0    0    0 1439 5234 9341 9182

In [21]:
dim=10

In [22]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_shape=(sent_length,)))
model.compile(optimizer='adam',loss='mse')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[-0.02983286, -0.01190758,  0.00403445, ..., -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445, ..., -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445, ..., -0.03986324,
         -0.01883723,  0.03751031],
        ...,
        [ 0.03253198,  0.03034526,  0.03505297, ...,  0.03794937,
         -0.0021493 ,  0.02258763],
        [-0.03494104,  0.02626133,  0.03919232, ..., -0.0415228 ,
         -0.04982864, -0.02914115],
        [ 0.00737519, -0.02685823,  0.03971542, ...,  0.03204726,
         -0.02539878,  0.03446029]],

       [[-0.02983286, -0.01190758,  0.00403445, ..., -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445, ..., -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445, ..., -0.03986324,
         -0.01883723,  0.03751031],
        ...,
        [ 0.04151925, -0.00762586,  0.00999754, ..., -

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 6936, 4395, 6829, 4659],
      dtype=int32)

In [25]:
print(embedded_docs[0].shape)

(10,)


In [26]:
import numpy as np

# Reshape the input to add a batch dimension
input_reshaped = np.expand_dims(embedded_docs[0], axis=0)



# Try predicting with the reshaped input
prediction = model.predict(input_reshaped)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[[-0.02983286, -0.01190758,  0.00403445,  0.04566384,
         -0.03448468,  0.02650335,  0.02358519, -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445,  0.04566384,
         -0.03448468,  0.02650335,  0.02358519, -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445,  0.04566384,
         -0.03448468,  0.02650335,  0.02358519, -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445,  0.04566384,
         -0.03448468,  0.02650335,  0.02358519, -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445,  0.04566384,
         -0.03448468,  0.02650335,  0.02358519, -0.03986324,
         -0.01883723,  0.03751031],
        [-0.02983286, -0.01190758,  0.00403445,  0.04566384,
         -0.03448468,  0.02650335,  0.02358519, -0.03986324,
         -0.01883723,  0.03751031],
        [-0.00539915, -0.02486259,  0.04475706,  0.0